# Generated by Django 4.1 on 2022-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_board_options_alter_bookmark_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
