# Generated by Django 4.1 on 2022-08-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_board_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
