# Generated by Django 4.1 on 2022-08-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_board_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-position',)},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ('-position',)},
        ),
        migrations.AlterModelOptions(
            name='bookmarkgroup',
            options={'ordering': ('-position',)},
        ),
    ]
