# Generated by Django 4.1 on 2022-08-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_alter_board_options_alter_bookmark_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.TextField(choices=[('slate', 'slate'), ('gray', 'gray'), ('zinc', 'zinc'), ('neutral', 'neutral'), ('stone', 'stone'), ('red', 'red'), ('orange', 'orange'), ('amber', 'amber'), ('yellow', 'yellow'), ('lime', 'lime'), ('green', 'green'), ('emerald', 'emerald'), ('teal', 'teal'), ('cyan', 'cyan'), ('sky', 'sky'), ('blue', 'blue'), ('indigo', 'indigo'), ('violet', 'violet'), ('purple', 'purple'), ('fuchsia', 'fuchsia'), ('pink', 'pink'), ('rose', 'rose')], default='neutral'),
        ),
    ]
