# Generated by Django 4.1 on 2022-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_accountsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkgroup',
            name='moved',
            field=models.BooleanField(default=False),
        ),
    ]
